# Generated by Django 3.0.6 on 2020-06-02 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('grade', models.CharField(choices=[('primary', 'Primary'), ('juniors', 'Junior Secondary'), ('seniors', 'Senior Secondary')], default='juniors', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1200)),
                ('address', models.CharField(max_length=200, verbose_name='Exact Address')),
                ('state', models.CharField(max_length=20, verbose_name='State')),
                ('local_govt', models.CharField(max_length=20, verbose_name='Local Government')),
                ('available', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('price', models.IntegerField(verbose_name='Price per Hour')),
                ('expertise', models.ManyToManyField(to='tutors.Subject')),
                ('info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
