# Generated by Django 3.0.6 on 2020-06-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0002_tutor_nick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=4, verbose_name='Price per Hour'),
        ),
    ]
