# Generated by Django 3.0.6 on 2020-06-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0003_auto_20200602_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Price per Hour'),
        ),
    ]
