# Generated by Django 3.0.6 on 2020-06-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0004_auto_20200602_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='price',
            field=models.IntegerField(verbose_name='Price per Hour'),
        ),
    ]
