# Generated by Django 3.0.6 on 2020-06-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0005_auto_20200602_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='phone_number',
            field=models.PositiveIntegerField(null=True, verbose_name='Phone Number'),
        ),
    ]
