# Generated by Django 3.0.6 on 2020-06-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0008_auto_20200603_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('fm', 'female')], default='m', max_length=6),
        ),
    ]
