# Generated by Django 3.0.6 on 2020-06-03 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0010_auto_20200603_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
