# Generated by Django 3.0.6 on 2020-06-04 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutors', '0012_auto_20200603_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Tutor_Info', to=settings.AUTH_USER_MODEL),
        ),
    ]
