# Generated by Django 3.0.6 on 2020-06-03 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutors', '0008_auto_20200603_0201'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Children',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('mr', 'Mr.'), ('ms', 'Miss.'), ('mrs', 'Mrs.'), ('master', 'Master.'), ('dr', 'Dr.')], default='master', max_length=10)),
                ('address', models.CharField(max_length=200, verbose_name='Exact Address')),
                ('state', models.CharField(max_length=20, verbose_name='State')),
                ('local_govt', models.CharField(max_length=20, verbose_name='Local Government')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Phone Number')),
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TutorRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_duration', models.IntegerField(verbose_name='Months_Needed')),
                ('location_needed', models.CharField(max_length=200, verbose_name='Tutoring_Location')),
                ('isAccepted', models.BooleanField(default=False)),
                ('inProgress', models.BooleanField(default=False)),
                ('isCompleted', models.BooleanField(default=False)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Requested_By', to='parents.Parent')),
                ('requested_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Requested_For', to='parents.Child')),
                ('requested_tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Requested_Tutor', to='tutors.Tutor')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parents.Parent'),
        ),
    ]
