# Generated by Django 3.0.6 on 2020-06-04 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parents', '0003_tutorrequest_medium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Parent_Info', to=settings.AUTH_USER_MODEL),
        ),
    ]
